---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 749250265631625216-dfU4IG7JSfyoaqktZQK2O7gUy6wkAZG
:access_token_secret: 14pPUINsTcBrxeFJ56rPD2sxMtD4IsRjOpLgUgxsZZrwz
